# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Gust < Formula
  desc "Command line weather app written in go"
  homepage "https://github.com/josephburgess/gust"
  url "https://github.com/josephburgess/gust/archive/refs/tags/v0.1.1.tar.gz"
  sha256 "666072469ac647bfe0c32dcca70be82017c2f5e726c71059399a2b32358fcfb3"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "./cmd/gust"
  end

  test do
    assert_match "Gust Weather", shell_output("#{bin}/gust -h", 2)
  end
end
